-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_4_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_4_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_4_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_0_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_5_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_5_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_5_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_1_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_6_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_6_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_6_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_2_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_7_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_7_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_7_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_3_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_17_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_17_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_17_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_13_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_18_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_18_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_18_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_14_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_19_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_19_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_19_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_15_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_28_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_28_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_28_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_24_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_29_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_29_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_29_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_25_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_30_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_30_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_30_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_26_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_31_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_31_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_31_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_27_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_8_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_8_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_8_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_9_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_9_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_9_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_10_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_10_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_10_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_11_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_11_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_11_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_20_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_20_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_20_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_16_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_21_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_21_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_21_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_22_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_22_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_22_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_23_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_23_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_23_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_32_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_32_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_32_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_33_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_33_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_33_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_34_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_34_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_34_o_ap_vld : OUT STD_LOGIC;
    kernel_data_V_7_35_i : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_35_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_7_35_o_ap_vld : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal line_buffer_Array_7_0_0_ce0 : STD_LOGIC;
    signal line_buffer_Array_7_0_0_we0 : STD_LOGIC;
    signal line_buffer_Array_7_0_0_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buffer_Array_7_1_0_ce0 : STD_LOGIC;
    signal line_buffer_Array_7_1_0_we0 : STD_LOGIC;
    signal line_buffer_Array_7_1_0_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buffer_Array_7_0_1_ce0 : STD_LOGIC;
    signal line_buffer_Array_7_0_1_we0 : STD_LOGIC;
    signal line_buffer_Array_7_0_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buffer_Array_7_1_1_ce0 : STD_LOGIC;
    signal line_buffer_Array_7_1_1_we0 : STD_LOGIC;
    signal line_buffer_Array_7_1_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buffer_Array_7_0_2_ce0 : STD_LOGIC;
    signal line_buffer_Array_7_0_2_we0 : STD_LOGIC;
    signal line_buffer_Array_7_0_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buffer_Array_7_1_2_ce0 : STD_LOGIC;
    signal line_buffer_Array_7_1_2_we0 : STD_LOGIC;
    signal line_buffer_Array_7_1_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buffer_Array_7_0_3_ce0 : STD_LOGIC;
    signal line_buffer_Array_7_0_3_we0 : STD_LOGIC;
    signal line_buffer_Array_7_0_3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buffer_Array_7_1_3_ce0 : STD_LOGIC;
    signal line_buffer_Array_7_1_3_we0 : STD_LOGIC;
    signal line_buffer_Array_7_1_3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    line_buffer_Array_7_0_0_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW
    generic map (
        DataWidth => 16,
        AddressRange => 31,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv5_1E,
        ce0 => line_buffer_Array_7_0_0_ce0,
        we0 => line_buffer_Array_7_0_0_we0,
        d0 => p_read,
        q0 => line_buffer_Array_7_0_0_q0);

    line_buffer_Array_7_1_0_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW
    generic map (
        DataWidth => 16,
        AddressRange => 31,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv5_1E,
        ce0 => line_buffer_Array_7_1_0_ce0,
        we0 => line_buffer_Array_7_1_0_we0,
        d0 => line_buffer_Array_7_0_0_q0,
        q0 => line_buffer_Array_7_1_0_q0);

    line_buffer_Array_7_0_1_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW
    generic map (
        DataWidth => 16,
        AddressRange => 31,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv5_1E,
        ce0 => line_buffer_Array_7_0_1_ce0,
        we0 => line_buffer_Array_7_0_1_we0,
        d0 => p_read1,
        q0 => line_buffer_Array_7_0_1_q0);

    line_buffer_Array_7_1_1_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW
    generic map (
        DataWidth => 16,
        AddressRange => 31,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv5_1E,
        ce0 => line_buffer_Array_7_1_1_ce0,
        we0 => line_buffer_Array_7_1_1_we0,
        d0 => line_buffer_Array_7_0_1_q0,
        q0 => line_buffer_Array_7_1_1_q0);

    line_buffer_Array_7_0_2_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW
    generic map (
        DataWidth => 16,
        AddressRange => 31,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv5_1E,
        ce0 => line_buffer_Array_7_0_2_ce0,
        we0 => line_buffer_Array_7_0_2_we0,
        d0 => p_read2,
        q0 => line_buffer_Array_7_0_2_q0);

    line_buffer_Array_7_1_2_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW
    generic map (
        DataWidth => 16,
        AddressRange => 31,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv5_1E,
        ce0 => line_buffer_Array_7_1_2_ce0,
        we0 => line_buffer_Array_7_1_2_we0,
        d0 => line_buffer_Array_7_0_2_q0,
        q0 => line_buffer_Array_7_1_2_q0);

    line_buffer_Array_7_0_3_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW
    generic map (
        DataWidth => 16,
        AddressRange => 31,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv5_1E,
        ce0 => line_buffer_Array_7_0_3_ce0,
        we0 => line_buffer_Array_7_0_3_we0,
        d0 => p_read3,
        q0 => line_buffer_Array_7_0_3_q0);

    line_buffer_Array_7_1_3_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config7_s_line_buffer_Array_7_lbW
    generic map (
        DataWidth => 16,
        AddressRange => 31,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv5_1E,
        ce0 => line_buffer_Array_7_1_3_ce0,
        we0 => line_buffer_Array_7_1_3_we0,
        d0 => line_buffer_Array_7_0_3_q0,
        q0 => line_buffer_Array_7_1_3_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_ce)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_0 <= kernel_data_V_7_4_i;

    kernel_data_V_7_0_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_0_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_1 <= kernel_data_V_7_5_i;

    kernel_data_V_7_10_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_10_i, line_buffer_Array_7_1_2_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_10_o <= line_buffer_Array_7_1_2_q0;
        else 
            kernel_data_V_7_10_o <= kernel_data_V_7_10_i;
        end if; 
    end process;


    kernel_data_V_7_10_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_10_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_10_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_11_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_11_i, line_buffer_Array_7_1_3_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_11_o <= line_buffer_Array_7_1_3_q0;
        else 
            kernel_data_V_7_11_o <= kernel_data_V_7_11_i;
        end if; 
    end process;


    kernel_data_V_7_11_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_11_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_11_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_13 <= kernel_data_V_7_17_i;

    kernel_data_V_7_13_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_13_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_13_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_14 <= kernel_data_V_7_18_i;

    kernel_data_V_7_14_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_14_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_15 <= kernel_data_V_7_19_i;

    kernel_data_V_7_15_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_15_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_16 <= kernel_data_V_7_20_i;

    kernel_data_V_7_16_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_16_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_16_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_17_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_17_i, kernel_data_V_7_21_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_17_o <= kernel_data_V_7_21_i;
        else 
            kernel_data_V_7_17_o <= kernel_data_V_7_17_i;
        end if; 
    end process;


    kernel_data_V_7_17_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_17_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_17_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_18_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_18_i, kernel_data_V_7_22_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_18_o <= kernel_data_V_7_22_i;
        else 
            kernel_data_V_7_18_o <= kernel_data_V_7_18_i;
        end if; 
    end process;


    kernel_data_V_7_18_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_18_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_18_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_19_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_19_i, kernel_data_V_7_23_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_19_o <= kernel_data_V_7_23_i;
        else 
            kernel_data_V_7_19_o <= kernel_data_V_7_19_i;
        end if; 
    end process;


    kernel_data_V_7_19_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_19_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_19_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_1_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_1_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_2 <= kernel_data_V_7_6_i;

    kernel_data_V_7_20_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_20_i, line_buffer_Array_7_0_0_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_20_o <= line_buffer_Array_7_0_0_q0;
        else 
            kernel_data_V_7_20_o <= kernel_data_V_7_20_i;
        end if; 
    end process;


    kernel_data_V_7_20_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_20_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_20_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_21_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_21_i, line_buffer_Array_7_0_1_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_21_o <= line_buffer_Array_7_0_1_q0;
        else 
            kernel_data_V_7_21_o <= kernel_data_V_7_21_i;
        end if; 
    end process;


    kernel_data_V_7_21_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_21_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_21_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_22_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_22_i, line_buffer_Array_7_0_2_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_22_o <= line_buffer_Array_7_0_2_q0;
        else 
            kernel_data_V_7_22_o <= kernel_data_V_7_22_i;
        end if; 
    end process;


    kernel_data_V_7_22_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_22_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_22_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_23_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_23_i, line_buffer_Array_7_0_3_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_23_o <= line_buffer_Array_7_0_3_q0;
        else 
            kernel_data_V_7_23_o <= kernel_data_V_7_23_i;
        end if; 
    end process;


    kernel_data_V_7_23_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_23_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_23_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_24 <= kernel_data_V_7_28_i;

    kernel_data_V_7_24_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_24_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_24_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_25 <= kernel_data_V_7_29_i;

    kernel_data_V_7_25_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_25_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_25_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_26 <= kernel_data_V_7_30_i;

    kernel_data_V_7_26_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_26_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_26_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_27 <= kernel_data_V_7_31_i;

    kernel_data_V_7_27_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_27_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_27_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_28_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_28_i, kernel_data_V_7_32_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_28_o <= kernel_data_V_7_32_i;
        else 
            kernel_data_V_7_28_o <= kernel_data_V_7_28_i;
        end if; 
    end process;


    kernel_data_V_7_28_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_28_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_28_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_29_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_29_i, kernel_data_V_7_33_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_29_o <= kernel_data_V_7_33_i;
        else 
            kernel_data_V_7_29_o <= kernel_data_V_7_29_i;
        end if; 
    end process;


    kernel_data_V_7_29_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_29_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_29_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_2_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_2_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    kernel_data_V_7_3 <= kernel_data_V_7_7_i;

    kernel_data_V_7_30_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_30_i, kernel_data_V_7_34_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_30_o <= kernel_data_V_7_34_i;
        else 
            kernel_data_V_7_30_o <= kernel_data_V_7_30_i;
        end if; 
    end process;


    kernel_data_V_7_30_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_30_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_30_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_31_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_31_i, kernel_data_V_7_35_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_31_o <= kernel_data_V_7_35_i;
        else 
            kernel_data_V_7_31_o <= kernel_data_V_7_31_i;
        end if; 
    end process;


    kernel_data_V_7_31_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_31_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_31_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_32_o_assign_proc : process(ap_CS_fsm_state1, p_read, kernel_data_V_7_32_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_32_o <= p_read;
        else 
            kernel_data_V_7_32_o <= kernel_data_V_7_32_i;
        end if; 
    end process;


    kernel_data_V_7_32_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_32_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_32_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_33_o_assign_proc : process(ap_CS_fsm_state1, p_read1, kernel_data_V_7_33_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_33_o <= p_read1;
        else 
            kernel_data_V_7_33_o <= kernel_data_V_7_33_i;
        end if; 
    end process;


    kernel_data_V_7_33_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_33_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_33_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_34_o_assign_proc : process(ap_CS_fsm_state1, p_read2, kernel_data_V_7_34_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_34_o <= p_read2;
        else 
            kernel_data_V_7_34_o <= kernel_data_V_7_34_i;
        end if; 
    end process;


    kernel_data_V_7_34_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_34_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_34_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_35_o_assign_proc : process(ap_CS_fsm_state1, p_read3, kernel_data_V_7_35_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_35_o <= p_read3;
        else 
            kernel_data_V_7_35_o <= kernel_data_V_7_35_i;
        end if; 
    end process;


    kernel_data_V_7_35_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_35_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_35_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_3_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_3_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_4_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_4_i, kernel_data_V_7_8_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_4_o <= kernel_data_V_7_8_i;
        else 
            kernel_data_V_7_4_o <= kernel_data_V_7_4_i;
        end if; 
    end process;


    kernel_data_V_7_4_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_4_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_4_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_5_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_5_i, kernel_data_V_7_9_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_5_o <= kernel_data_V_7_9_i;
        else 
            kernel_data_V_7_5_o <= kernel_data_V_7_5_i;
        end if; 
    end process;


    kernel_data_V_7_5_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_5_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_5_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_6_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_6_i, kernel_data_V_7_10_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_6_o <= kernel_data_V_7_10_i;
        else 
            kernel_data_V_7_6_o <= kernel_data_V_7_6_i;
        end if; 
    end process;


    kernel_data_V_7_6_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_6_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_6_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_7_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_7_i, kernel_data_V_7_11_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_7_o <= kernel_data_V_7_11_i;
        else 
            kernel_data_V_7_7_o <= kernel_data_V_7_7_i;
        end if; 
    end process;


    kernel_data_V_7_7_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_7_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_7_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_8_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_8_i, line_buffer_Array_7_1_0_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_8_o <= line_buffer_Array_7_1_0_q0;
        else 
            kernel_data_V_7_8_o <= kernel_data_V_7_8_i;
        end if; 
    end process;


    kernel_data_V_7_8_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_8_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_8_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    kernel_data_V_7_9_o_assign_proc : process(ap_CS_fsm_state1, kernel_data_V_7_9_i, line_buffer_Array_7_1_1_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_data_V_7_9_o <= line_buffer_Array_7_1_1_q0;
        else 
            kernel_data_V_7_9_o <= kernel_data_V_7_9_i;
        end if; 
    end process;


    kernel_data_V_7_9_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            kernel_data_V_7_9_o_ap_vld <= ap_const_logic_1;
        else 
            kernel_data_V_7_9_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_0_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_0_0_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_0_0_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_0_0_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_0_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_0_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_0_1_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_0_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_0_1_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_0_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_0_2_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_0_2_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_0_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_0_2_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_0_2_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_0_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_0_3_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_0_3_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_0_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_0_3_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_0_3_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_0_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_1_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_1_0_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_1_0_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_1_0_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_1_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_1_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_1_1_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_1_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_1_1_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_1_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_1_2_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_1_2_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_1_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_1_2_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_1_2_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_1_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_1_3_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_1_3_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_1_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_7_1_3_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_7_1_3_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_7_1_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
