<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="15">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>conv_2d_cl_array_ap_fixed_2u_array_ap_fixed_16_6_5_3_0_2u_config12_s</name>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>layer11_out</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName>FIFO</coreName>
              <coreId>1769239903</coreId>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>layer12_out</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName>FIFO</coreName>
              <coreId>1769239903</coreId>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>11</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>32</id>
              <name>br_ln24</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>24</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_config12_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</second>
                      </first>
                      <second>24</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>742273056</coreId>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>51</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>1.58</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>34</id>
              <name>indvar_flatten</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>24</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_config12_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</second>
                      </first>
                      <second>24</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>539770416</coreId>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>53</item>
            <item>54</item>
            <item>55</item>
            <item>56</item>
          </oprand_edges>
          <opcode>phi</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>35</id>
              <name>add_ln24</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>24</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_config12_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</second>
                      </first>
                      <second>24</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>add_ln24_fu_163_p2</rtlName>
              <control>auto</control>
              <opType>add</opType>
              <implIndex>fabric</implIndex>
              <coreName>Adder</coreName>
              <coreId>1</coreId>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>57</item>
            <item>59</item>
          </oprand_edges>
          <opcode>add</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>1.91</m_delay>
          <m_topoIndex>3</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>36</id>
              <name>icmp_ln24</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>24</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_config12_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</second>
                      </first>
                      <second>24</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>icmp_ln24_fu_169_p2</rtlName>
              <control/>
              <opType>icmp</opType>
              <implIndex/>
              <coreName/>
              <coreId>1869438831</coreId>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>60</item>
            <item>62</item>
          </oprand_edges>
          <opcode>icmp</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>1.55</m_delay>
          <m_topoIndex>4</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>37</id>
              <name>br_ln24</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>24</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_config12_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</second>
                      </first>
                      <second>24</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>1869438831</coreId>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>63</item>
            <item>64</item>
            <item>65</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>5</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>43</id>
              <name>layer11_out_read</name>
              <fileName>/mnt/Data/Xilinx/Vitis_HLS/2020.2/common/technology/autopilot/hls_stream_39.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>145</lineNumber>
              <contextFuncName>read</contextFuncName>
              <contextNormFuncName>read</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/mnt/Data/Xilinx/Vitis_HLS/2020.2/common/technology/autopilot/hls_stream_39.h</first>
                        <second>read</second>
                      </first>
                      <second>145</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control>auto</control>
              <opType>fifo</opType>
              <implIndex>memory</implIndex>
              <coreName>FIFO</coreName>
              <coreId>78</coreId>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>67</item>
            <item>68</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>2.18</m_delay>
          <m_topoIndex>6</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>44</id>
              <name>trunc_ln145</name>
              <fileName>/mnt/Data/Xilinx/Vitis_HLS/2020.2/common/technology/autopilot/hls_stream_39.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>145</lineNumber>
              <contextFuncName>read</contextFuncName>
              <contextNormFuncName>read</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/mnt/Data/Xilinx/Vitis_HLS/2020.2/common/technology/autopilot/hls_stream_39.h</first>
                        <second>read</second>
                      </first>
                      <second>145</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s_fu_107_p_read</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>976630375</coreId>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>69</item>
          </oprand_edges>
          <opcode>trunc</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>7</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>45</id>
              <name>trunc_ln145_s</name>
              <fileName>/mnt/Data/Xilinx/Vitis_HLS/2020.2/common/technology/autopilot/hls_stream_39.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>145</lineNumber>
              <contextFuncName>read</contextFuncName>
              <contextNormFuncName>read</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/mnt/Data/Xilinx/Vitis_HLS/2020.2/common/technology/autopilot/hls_stream_39.h</first>
                        <second>read</second>
                      </first>
                      <second>145</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s_fu_107_p_read1</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>132</coreId>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>71</item>
            <item>72</item>
            <item>74</item>
            <item>76</item>
          </oprand_edges>
          <opcode>partselect</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>8</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>46</id>
              <name>_ln31</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>31</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_config12_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</second>
                      </first>
                      <second>31</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s_fu_107</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>129</coreId>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>28</count>
            <item_version>0</item_version>
            <item>78</item>
            <item>79</item>
            <item>80</item>
            <item>81</item>
            <item>83</item>
            <item>84</item>
            <item>85</item>
            <item>86</item>
            <item>87</item>
            <item>88</item>
            <item>89</item>
            <item>90</item>
            <item>91</item>
            <item>92</item>
            <item>93</item>
            <item>94</item>
            <item>95</item>
            <item>96</item>
            <item>97</item>
            <item>98</item>
            <item>99</item>
            <item>100</item>
            <item>101</item>
            <item>102</item>
            <item>103</item>
            <item>104</item>
            <item>105</item>
            <item>106</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>9</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>47</id>
              <name>br_ln0</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>1713399158</coreId>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>82</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>10</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>49</id>
              <name>_ln79</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>79</lineNumber>
              <contextFuncName>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_cl_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_nnet_array_ap_fixed_16_6_AP_TRN_AP_WRAP_0_2_config12_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/mnt/Data/digital_design/AI_NPU_CNN_3/Covid19-CNN/pruned_cnn</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;16, 6, AP_TRN, AP_WRAP, 0&amp;gt;, 2&amp;gt;, config12&amp;gt;</second>
                      </first>
                      <second>79</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>1014587762</coreId>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>11</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_14">
          <Value>
            <Obj>
              <type>2</type>
              <id>52</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>1818850421</coreId>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_15">
          <Value>
            <Obj>
              <type>2</type>
              <id>58</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>0</coreId>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_16">
          <Value>
            <Obj>
              <type>2</type>
              <id>61</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>1769239903</coreId>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>196</content>
        </item>
        <item class_id_reference="16" object_id="_17">
          <Value>
            <Obj>
              <type>2</type>
              <id>73</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>1769239903</coreId>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>16</content>
        </item>
        <item class_id_reference="16" object_id="_18">
          <Value>
            <Obj>
              <type>2</type>
              <id>75</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>97</coreId>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>31</content>
        </item>
        <item class_id_reference="16" object_id="_19">
          <Value>
            <Obj>
              <type>2</type>
              <id>77</id>
              <name>compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <coreId>49</coreId>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:compute_output_buffer_2d&lt;array,array&lt;ap_fixed&lt;16,6,5,3,0&gt;,2u&gt;,config12&gt;&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_20">
          <Obj>
            <type>3</type>
            <id>33</id>
            <name>codeRepl</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <contextNormFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <control/>
            <opType/>
            <implIndex/>
            <coreName/>
            <coreId>1633970549</coreId>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>32</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_21">
          <Obj>
            <type>3</type>
            <id>38</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <contextNormFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <control/>
            <opType/>
            <implIndex/>
            <coreName/>
            <coreId>1633970549</coreId>
          </Obj>
          <node_objs>
            <count>4</count>
            <item_version>0</item_version>
            <item>34</item>
            <item>35</item>
            <item>36</item>
            <item>37</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_22">
          <Obj>
            <type>3</type>
            <id>48</id>
            <name>.split3</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <contextNormFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <control/>
            <opType/>
            <implIndex/>
            <coreName/>
            <coreId>49</coreId>
          </Obj>
          <node_objs>
            <count>5</count>
            <item_version>0</item_version>
            <item>43</item>
            <item>44</item>
            <item>45</item>
            <item>46</item>
            <item>47</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_23">
          <Obj>
            <type>3</type>
            <id>50</id>
            <name>_ZN4nnet25conv_2d_buffer_latency_clINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EELj2EEES6_8config12EEvRN3hls6streamIT_Li0EEERNS9_IT0_Li0EEEPNT1_8weight_tEPNSG_6bias_tE.exit</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <contextNormFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <control/>
            <opType/>
            <implIndex/>
            <coreName/>
            <coreId>1834970975</coreId>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>49</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>50</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_24">
          <id>51</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>32</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>53</id>
          <edge_type>1</edge_type>
          <source_obj>52</source_obj>
          <sink_obj>34</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>54</id>
          <edge_type>2</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>34</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>55</id>
          <edge_type>1</edge_type>
          <source_obj>35</source_obj>
          <sink_obj>34</sink_obj>
          <is_back_edge>1</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>56</id>
          <edge_type>2</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>34</sink_obj>
          <is_back_edge>1</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>57</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>35</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>59</id>
          <edge_type>1</edge_type>
          <source_obj>58</source_obj>
          <sink_obj>35</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>60</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>62</id>
          <edge_type>1</edge_type>
          <source_obj>61</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>63</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>37</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>64</id>
          <edge_type>2</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>37</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>65</id>
          <edge_type>2</edge_type>
          <source_obj>50</source_obj>
          <sink_obj>37</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>68</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>43</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>69</id>
          <edge_type>1</edge_type>
          <source_obj>43</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>72</id>
          <edge_type>1</edge_type>
          <source_obj>43</source_obj>
          <sink_obj>45</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>74</id>
          <edge_type>1</edge_type>
          <source_obj>73</source_obj>
          <sink_obj>45</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>76</id>
          <edge_type>1</edge_type>
          <source_obj>75</source_obj>
          <sink_obj>45</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>78</id>
          <edge_type>1</edge_type>
          <source_obj>77</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>79</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>80</id>
          <edge_type>1</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>81</id>
          <edge_type>1</edge_type>
          <source_obj>45</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>82</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>47</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>83</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>84</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>85</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>86</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>87</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>88</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>89</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>90</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>91</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>92</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>93</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>94</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>95</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>96</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>97</id>
          <edge_type>1</edge_type>
          <source_obj>18</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>98</id>
          <edge_type>1</edge_type>
          <source_obj>19</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>99</id>
          <edge_type>1</edge_type>
          <source_obj>21</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>100</id>
          <edge_type>1</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>101</id>
          <edge_type>1</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>102</id>
          <edge_type>1</edge_type>
          <source_obj>24</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_66">
          <id>103</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_67">
          <id>104</id>
          <edge_type>1</edge_type>
          <source_obj>27</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_68">
          <id>105</id>
          <edge_type>1</edge_type>
          <source_obj>28</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_69">
          <id>106</id>
          <edge_type>1</edge_type>
          <source_obj>29</source_obj>
          <sink_obj>46</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_70">
          <id>169</id>
          <edge_type>2</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>38</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_71">
          <id>170</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>50</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_72">
          <id>171</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>48</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_73">
          <id>172</id>
          <edge_type>2</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>38</sink_obj>
          <is_back_edge>1</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_74">
        <mId>1</mId>
        <mTag>conv_2d_cl&lt;array&lt;ap_fixed,2u&gt;,array&lt;ap_fixed&lt;16,6,5,3,0&gt;,2u&gt;,config12&gt;</mTag>
        <mNormTag>conv_2d_cl_array_ap_fixed_2u_array_ap_fixed_16_6_5_3_0_2u_config12_s</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>3</count>
          <item_version>0</item_version>
          <item>2</item>
          <item>3</item>
          <item>4</item>
        </sub_regions>
        <basic_blocks>
          <count>0</count>
          <item_version>0</item_version>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>1571</mMinLatency>
        <mMaxLatency>1571</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_75">
        <mId>2</mId>
        <mTag>Entry</mTag>
        <mNormTag>Entry</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>0</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_76">
        <mId>3</mId>
        <mTag>ReadInputHeight_ReadInputWidth</mTag>
        <mNormTag>ReadInputHeight_ReadInputWidth</mNormTag>
        <mType>1</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>2</count>
          <item_version>0</item_version>
          <item>38</item>
          <item>48</item>
        </basic_blocks>
        <mII>8</mII>
        <mDepth>10</mDepth>
        <mMinTripCount>196</mMinTripCount>
        <mMaxTripCount>196</mMaxTripCount>
        <mMinLatency>1569</mMinLatency>
        <mMaxLatency>1569</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_77">
        <mId>4</mId>
        <mTag>Return</mTag>
        <mNormTag>Return</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>50</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>0</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_78">
      <states class_id="25" tracking_level="0" version="0">
        <count>12</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_79">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_80">
              <id>30</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_81">
              <id>31</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_82">
              <id>32</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_83">
          <id>2</id>
          <operations>
            <count>4</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_84">
              <id>34</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_85">
              <id>35</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_86">
              <id>36</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_87">
              <id>37</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_88">
          <id>3</id>
          <operations>
            <count>4</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_89">
              <id>43</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_90">
              <id>44</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_91">
              <id>45</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_92">
              <id>46</id>
              <stage>9</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_93">
          <id>4</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_94">
              <id>46</id>
              <stage>8</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_95">
          <id>5</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_96">
              <id>46</id>
              <stage>7</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_97">
          <id>6</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_98">
              <id>46</id>
              <stage>6</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_99">
          <id>7</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_100">
              <id>46</id>
              <stage>5</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_101">
          <id>8</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_102">
              <id>46</id>
              <stage>4</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_103">
          <id>9</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_104">
              <id>46</id>
              <stage>3</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_105">
          <id>10</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_106">
              <id>46</id>
              <stage>2</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_107">
          <id>11</id>
          <operations>
            <count>6</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_108">
              <id>39</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_109">
              <id>40</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_110">
              <id>41</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_111">
              <id>42</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_112">
              <id>46</id>
              <stage>1</stage>
              <latency>9</latency>
            </item>
            <item class_id_reference="28" object_id="_113">
              <id>47</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_114">
          <id>12</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_115">
              <id>49</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>12</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_116">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>-1</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_117">
          <inState>3</inState>
          <outState>4</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_118">
          <inState>4</inState>
          <outState>5</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_119">
          <inState>5</inState>
          <outState>6</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_120">
          <inState>6</inState>
          <outState>7</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_121">
          <inState>7</inState>
          <outState>8</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_122">
          <inState>8</inState>
          <outState>9</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_123">
          <inState>9</inState>
          <outState>10</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_124">
          <inState>10</inState>
          <outState>11</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_125">
          <inState>11</inState>
          <outState>2</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_126">
          <inState>2</inState>
          <outState>12</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="34" tracking_level="0" version="0">
                  <first class_id="35" tracking_level="0" version="0">
                    <first>36</first>
                    <second>0</second>
                  </first>
                  <second>0</second>
                </item>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_127">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>
                    <first>36</first>
                    <second>0</second>
                  </first>
                  <second>1</second>
                </item>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="36" tracking_level="1" version="0" object_id="_128">
      <dp_component_resource class_id="37" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="38" tracking_level="0" version="0">
          <first>grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s_fu_107 (compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s)</first>
          <second class_id="39" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="40" tracking_level="0" version="0">
              <first>DSP</first>
              <second>22</second>
            </item>
            <item>
              <first>FF</first>
              <second>3278</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1365</second>
            </item>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>8</count>
        <item_version>0</item_version>
        <item>
          <first>add_ln24_fu_163_p2 ( + ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>8</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>15</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_block_pp0_stage1_11001 ( or ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_block_pp0_stage1_11001_ignoreCallOp23 ( and ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_block_state1 ( or ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_block_state11_pp0_stage1_iter1 ( and ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_block_state3_pp0_stage1_iter0 ( and ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_enable_pp0 ( xor ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>icmp_ln24_fu_169_p2 ( icmp ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>8</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>7</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>11</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>9</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>11</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>11</second>
            </item>
            <item>
              <first>LUT</first>
              <second>59</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_enable_reg_pp0_iter1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_phi_mux_indvar_flatten_phi_fu_100_p4</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>8</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>16</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>indvar_flatten_reg_96</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>8</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>16</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>layer11_out_blk_n</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>layer12_out_blk_n</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>layer12_out_write</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>real_start</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>10</count>
        <item_version>0</item_version>
        <item>
          <first>add_ln24_reg_191</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>8</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>8</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>10</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>10</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_enable_reg_pp0_iter0</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_enable_reg_pp0_iter1</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s_fu_107_ap_start_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>icmp_ln24_reg_196</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>icmp_ln24_reg_196_pp0_iter1_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>indvar_flatten_reg_96</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>8</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>8</second>
            </item>
          </second>
        </item>
        <item>
          <first>start_once_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s_fu_107</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="41" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="42" tracking_level="0" version="0">
          <first>grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s_fu_107 (compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>46</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>add_ln24_fu_163_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>35</item>
          </second>
        </item>
        <item>
          <first>icmp_ln24_fu_169_p2 ( icmp ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>36</item>
          </second>
        </item>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="43" tracking_level="0" version="0">
      <count>11</count>
      <item_version>0</item_version>
      <item class_id="44" tracking_level="0" version="0">
        <first>32</first>
        <second class_id="45" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>34</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>35</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>37</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>43</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>44</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>45</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>46</first>
        <second>
          <first>2</first>
          <second>8</second>
        </second>
      </item>
      <item>
        <first>47</first>
        <second>
          <first>10</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>49</first>
        <second>
          <first>11</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="46" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="47" tracking_level="0" version="0">
        <first>33</first>
        <second class_id="48" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>38</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>48</first>
        <second>
          <first>2</first>
          <second>10</second>
        </second>
      </item>
      <item>
        <first>50</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="49" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="50" tracking_level="1" version="0" object_id="_129">
        <region_name>ReadInputHeight_ReadInputWidth</region_name>
        <basic_blocks>
          <count>2</count>
          <item_version>0</item_version>
          <item>38</item>
          <item>48</item>
        </basic_blocks>
        <nodes>
          <count>0</count>
          <item_version>0</item_version>
        </nodes>
        <anchor_node>-1</anchor_node>
        <region_type>8</region_type>
        <interval>8</interval>
        <pipe_depth>10</pipe_depth>
      </item>
    </regions>
    <dp_fu_nodes class_id="51" tracking_level="0" version="0">
      <count>7</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>90</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>43</item>
        </second>
      </item>
      <item>
        <first>100</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
      <item>
        <first>107</first>
        <second>
          <count>9</count>
          <item_version>0</item_version>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
        </second>
      </item>
      <item>
        <first>163</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>35</item>
        </second>
      </item>
      <item>
        <first>169</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>175</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>180</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>45</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="54" tracking_level="0" version="0">
      <count>5</count>
      <item_version>0</item_version>
      <item class_id="55" tracking_level="0" version="0">
        <first>add_ln24_fu_163</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>35</item>
        </second>
      </item>
      <item>
        <first>icmp_ln24_fu_169</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>indvar_flatten_phi_fu_100</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
      <item>
        <first>trunc_ln145_fu_175</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>trunc_ln145_s_fu_180</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>45</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_2u_config12_s_fu_107</first>
        <second>
          <count>9</count>
          <item_version>0</item_version>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
          <item>46</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>layer11_out_read_read_fu_90</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>43</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="56" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="57" tracking_level="0" version="0">
        <first class_id="58" tracking_level="0" version="0">
          <first>line_buffer_Array_5_0_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>46</item>
        </second>
      </item>
      <item>
        <first>
          <first>line_buffer_Array_5_0_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>46</item>
        </second>
      </item>
      <item>
        <first>
          <first>line_buffer_Array_5_1_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>46</item>
        </second>
      </item>
      <item>
        <first>
          <first>line_buffer_Array_5_1_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>46</item>
        </second>
      </item>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>96</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
      <item>
        <first>191</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>35</item>
        </second>
      </item>
      <item>
        <first>196</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>add_ln24_reg_191</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>35</item>
        </second>
      </item>
      <item>
        <first>icmp_ln24_reg_196</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>indvar_flatten_reg_96</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>96</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>indvar_flatten_reg_96</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="59" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="60" tracking_level="0" version="0">
        <first>layer11_out</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>43</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>layer12_out</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>46</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>1</first>
        <second>
          <first>1150</first>
          <second>7</second>
        </second>
      </item>
      <item>
        <first>2</first>
        <second>
          <first>1151</first>
          <second>7</second>
        </second>
      </item>
    </port2core>
    <node2core>
      <count>4</count>
      <item_version>0</item_version>
      <item>
        <first>35</first>
        <second>
          <first>8</first>
          <second>4</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>45</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>43</first>
        <second>
          <first>1150</first>
          <second>7</second>
        </second>
      </item>
      <item>
        <first>46</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
    </node2core>
  </syndb>
</boost_serialization>
